In [27]:
import pandas as pd
import numpy as np

data1 = pd.read_csv("samsung.csv")
data2 = pd.read_csv("lge.csv")
data3 = pd.read_csv("kt&g.csv")
data4 = pd.read_csv("cj.csv")
data5 = pd.read_csv("naver.csv")
data6 = pd.read_csv("hyundai.csv")
data7 = pd.read_csv("sk_innovation.csv")
data8 = pd.read_csv("sktele.csv")
data9 = pd.read_csv("kakao.csv")
data10 = pd.read_csv("kepco.csv")

data = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10], ignore_index = True)

print(len(data1))
print(len(data2))
print(len(data3))
print(len(data4))
print(len(data5))
print(len(data6))
print(len(data7))
print(len(data8))
print(len(data9))
print(len(data10))
print(len(data))

print()


star = list()
promotion = list()
welfare = list()
worklife = list()
culture = list()
ceo = list()

for i in range(len(data)):
    star.append(data.loc[i]['star'])
    promotion.append(data.loc[i]['promotion'])
    welfare.append(data.loc[i]['welfare'])
    worklife.append(data.loc[i]['worklife'])
    culture.append(data.loc[i]['culture'])
    ceo.append(data.loc[i]['ceo'])
   
# correlation coefficient of each elements 
print(np.corrcoef([star, promotion, welfare, worklife, culture, ceo]))

3375
510
132
510
506
1007
126
373
284
760
7583

[[1.         0.47868585 0.45969194 0.48410946 0.55353313 0.56392168]
 [0.47868585 1.         0.34164067 0.22939093 0.37577637 0.43824547]
 [0.45969194 0.34164067 1.         0.18091394 0.29168667 0.34959097]
 [0.48410946 0.22939093 0.18091394 1.         0.500818   0.41300214]
 [0.55353313 0.37577637 0.29168667 0.500818   1.         0.56353631]
 [0.56392168 0.43824547 0.34959097 0.41300214 0.56353631 1.        ]]
